/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controleur.Controleur;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modele.Link;
import modele.PHPClass;
import modele.Page;

/**
 *
 * @author Jules
 */
public class FenetrePrincipal extends javax.swing.JFrame {

    private Controleur controleur;
    
    private DefaultListModel list1;
    private DefaultListModel list2;
    private DefaultListModel list3;
    private DefaultListModel list4;
    
    /**
     * Creates new form FenetrePrincipal
     */
    public FenetrePrincipal(Controleur c) {
        this.controleur = c;
        initComponents();
        initLists();
        demanderNomProjet();
        actualiser();
        jTextField2.setEnabled(false);
    }
    
    private void initLists() {
        list1 = new DefaultListModel();
        list2 = new DefaultListModel();
        list3 = new DefaultListModel();
        list4 = new DefaultListModel();
        jList1.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        jList2.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        jList3.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        jList4.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        jList1.setModel(list1);
        jList2.setModel(list2);
        jList3.setModel(list3);
        jList4.setModel(list4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jList3.setMinimumSize(new java.awt.Dimension(200, 100));
        jList3.setPreferredSize(new java.awt.Dimension(250, 120));
        jList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jList3);

        jButton7.setText("Ajouter Page");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Modifier Page");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Supprimer Page");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Menu");

        jList4.setPreferredSize(new java.awt.Dimension(250, 120));
        jScrollPane4.setViewportView(jList4);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Liste des liens head");

        jButton10.setText("Ajouter Lien");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Modifier Lien");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Supprimer Lien");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel8.setText("Titre du site :");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton13.setText("Modifier");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(218, 218, 218)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)))
                .addGap(93, 93, 93))
        );

        jTabbedPane1.addTab("Structure du site", jPanel1);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jList1.setToolTipText("");
        jList1.setPreferredSize(new java.awt.Dimension(250, 120));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Liste des classes");

        jButton1.setText("Ajouter Classe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier Classe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Supprimer Classe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jList2.setPreferredSize(new java.awt.Dimension(250, 120));
        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Attributs");

        jButton4.setText("Ajouter Attribut");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Modifier Attribut");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Supprimer Attribut");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6)))
                .addGap(94, 94, 94))
        );

        jTabbedPane1.addTab("Classes PHP", jPanel2);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New Project");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setLabel("Save Project");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Export Project");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Quit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        controleur.newProject();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // BOUTON MODIFIER CLASSE
        afficherFenetreModifierClasse();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // BOUTON AJOUTER ATTRIBUT
        afficherFenetreAjouterAttribut();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // BOUTON SUPPRIMER ATTRIBUT
        afficherFenetreSupprimerAttribut();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // BOUTON AJOUTER LIEN
        afficherFenetreAjouterLien();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // BOUTON MODIFIER LIEN
        afficherFenetreModifierLien();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // BOUTON AJOUTER PAGE
        afficherFenetreAjouterPage();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // BOUTON SUPPRIMER PAGE
        afficherFenetreSupprimerPage();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // CLICK SUR LA JLIST DES CLASSES PHP
        actualiser();
        actualiserList2();
    }//GEN-LAST:event_jList1MouseClicked

    private void jList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList3MouseClicked
        // CLICK SUR LA JLIST DES PAGES MENU
        actualiser();
    }//GEN-LAST:event_jList3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // BOUTON MODIFIER PAGE
        afficherFenetreModifierPage();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // BOUTON AJOUTER CLASSE
        afficherFenetreAjouterClasse();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // BOUTON SUPPRIMER LIEN
        afficherFenetreSupprimerLien();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // BOUTON SUPPRIMER CLASSE
        afficherFenetreSupprimerClasse();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // BOUTON ENREGISTRER SOUS
        afficherEnregistrerProjet();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // BOUTON MODIFIER ATTRIBUT
        afficherFenetreModifierAttribut();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            afficherFenetreExporterProjet();
        } catch (IOException ex) {
            Logger.getLogger(FenetrePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        controleur.quitter();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        // CLICK SUR LA LISTE DES ATTRIBUTS
        actualiser();
        actualiserList2();
    }//GEN-LAST:event_jList2MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        setNomSite();
        jTextField2.setEnabled(false);
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // SI ON APPUIE SUR ENTER
        if (evt.getKeyCode() == 10) {
            setNomSite();
            jTextField2.setEnabled(false);
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // BOUTON MODIFIER TITRE
        if (jTextField2.isEnabled()) {
            jTextField2.setEnabled(false);
            setNomSite();
        } else {
            jTextField2.setEnabled(true);
        }
    }//GEN-LAST:event_jButton13ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void actualiser() {

        // JLIST CLASSES
        if (jList1.getModel().getSize() == 1 ) {
            jList1.setSelectedIndex(0);
        }
        if (jList1.getSelectedIndices().length == 0) {
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        } else {
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
        }
        
        // JLIST ATTRIBUTS
        if (jList2.getModel().getSize() == 1) {
            jList2.setSelectedIndex(0);
        }
        if (jList1.getSelectedIndices().length == 0) {
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
        } else if (jList1.getSelectedIndices().length == 1 && jList2.getModel().getSize() == 0) {
            jButton4.setEnabled(true);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
        } else {
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
        }
        
        // JLIST PAGES MENU
        if (jList3.getModel().getSize() == 1) {
            jList3.setSelectedIndex(0);
        }
        if (jList3.getSelectedIndices().length == 0) {
            jButton8.setEnabled(false);
            jButton9.setEnabled(false);
        } else {
            jButton8.setEnabled(true);
            jButton9.setEnabled(true);
        }
        
        // JLIST LIENS HEAD
        if (jList4.getModel().getSize() == 1) {
            jList4.setSelectedIndex(0);
        }
        if (jList4.getSelectedIndices().length == 0) {
            jButton11.setEnabled(false);
            jButton12.setEnabled(false);
        } else {
            jButton11.setEnabled(true);
            jButton12.setEnabled(true);
        }
        
        controleur.afficherEtat();
    }
    
    private void afficherFenetreAjouterPage() {
        String nomPage = JOptionPane.showInputDialog(this, "Nom de la page", "", JOptionPane.QUESTION_MESSAGE);
        if (nomPage != null) {
            if (nomPage.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomPage)) {
                JOptionPane.showMessageDialog(this, "Cette page existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                controleur.getMenu().addPage(new Page(nomPage.replaceFirst(".", (nomPage.charAt(0) + "").toUpperCase())));
                list3.addElement(nomPage.replaceFirst(".", (nomPage.charAt(0) + "").toUpperCase()));
            }
        }
        actualiser();
    }

    private void afficherFenetreSupprimerPage() {
        String nomPage = (String) jList3.getSelectedValue();
        if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer la page : " + nomPage, "Supprimer page", JOptionPane.OK_CANCEL_OPTION) == 0) {
            controleur.getMenu().supprimerPage(nomPage);
            list3.removeElement(nomPage);
        }
        actualiser();
    }

    private void afficherFenetreModifierPage() {
        String oldNomPage = (String)jList3.getSelectedValue();
        String nomPage = JOptionPane.showInputDialog(this, "Nom de la page", oldNomPage);
        if (nomPage != null) {
            if (nomPage.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomPage)) {
                JOptionPane.showMessageDialog(this, "Cette page existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                controleur.getMenu().updatePage(oldNomPage, nomPage.replaceFirst(".", (nomPage.charAt(0) + "").toUpperCase()));
                list3.removeElement(oldNomPage);
                list3.addElement(nomPage.replaceFirst(".", (nomPage.charAt(0) + "").toUpperCase()));
            }
        }
        actualiser();    
    }

    private void afficherFenetreAjouterLien() {
        String nomLien = JOptionPane.showInputDialog(this, "Nom de la page", "", JOptionPane.QUESTION_MESSAGE);
        if (nomLien != null) {
            if (nomLien.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomLien)) {
                JOptionPane.showMessageDialog(this, "Ce lien existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                String[] possibleValues = {"Css", "Script"};
                String selectedValue = (String) JOptionPane.showInputDialog(null,
                        "Choose one", "Input",
                        JOptionPane.INFORMATION_MESSAGE, null,
                        possibleValues, possibleValues[0]);
                controleur.getMenu().addLink(new Link(nomLien, selectedValue));
                list4.addElement(nomLien + " : " + selectedValue);
            }
        }
        actualiser();
    }
    
    private void afficherFenetreSupprimerLien() {
        String nomLien = (String) jList4.getSelectedValue();
        if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer le lien : " + nomLien, "Supprimer lien", JOptionPane.OK_CANCEL_OPTION) == 0) {
            controleur.getMenu().removeLink(nomLien);
            list4.removeElement(nomLien);
        }
        actualiser();
    }

    private void afficherFenetreModifierLien() {
        String oldNomLien = ((String) jList4.getSelectedValue()).split(":")[0].trim();
        String nomLien = JOptionPane.showInputDialog(this, "Nom du lien : ", oldNomLien);
        if (nomLien != null) {
            if (nomLien.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomLien)) {
                JOptionPane.showMessageDialog(this, "Ce lien existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                String[] possibleValues = {"Css", "Script"};
                String selectedValue = (String) JOptionPane.showInputDialog(null,
                        "Choose one", "Input",
                        JOptionPane.INFORMATION_MESSAGE, null,
                        possibleValues, possibleValues[0]);
                controleur.getMenu().updateLink(oldNomLien, nomLien, selectedValue);
                list4.removeElement((String) jList4.getSelectedValue());
                list4.addElement(nomLien);
            }
        }
        actualiser();
    }

    private void afficherFenetreAjouterClasse() {
        String nomClasse = JOptionPane.showInputDialog(this, "Nom de la classe : ", "", JOptionPane.QUESTION_MESSAGE);
        if (nomClasse != null) {
            if (nomClasse.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomClasse)) {
                JOptionPane.showMessageDialog(this, "Cette classe existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                controleur.getPhpControleur().addClasse(new PHPClass(nomClasse.replaceFirst(".", (nomClasse.charAt(0) + "").toUpperCase())));
                list1.addElement(nomClasse.replaceFirst(".", (nomClasse.toUpperCase().charAt(0) + "").toUpperCase()));
            }
        }
        actualiser();
    }
    
    private void afficherFenetreSupprimerClasse() {
        String nomClasse = (String) jList1.getSelectedValue();
        if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer la page : " + nomClasse, "Supprimer page", JOptionPane.OK_CANCEL_OPTION) == 0) {
            controleur.getPhpControleur().removeClasse(nomClasse);
            list1.removeElement(nomClasse);
        }
        actualiser();
    }

    private void afficherFenetreModifierClasse() {
        String oldNomClasse = (String) jList1.getSelectedValue();
        String nomClasse = JOptionPane.showInputDialog(this, "Nom de la page", oldNomClasse);
        if (nomClasse != null) {
            if (nomClasse.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomClasse)) {
                JOptionPane.showMessageDialog(this, "Cette page existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                controleur.getPhpControleur().updateClasse(oldNomClasse, nomClasse.replaceFirst(".", (nomClasse.charAt(0) + "").toUpperCase()));
                list1.removeElement(oldNomClasse);
                list1.addElement(nomClasse.replaceFirst(".", (nomClasse.charAt(0) + "").toUpperCase()));
            }
        }
        actualiser();
    }
    
    private void afficherFenetreAjouterAttribut() {
        String nomAttribut = JOptionPane.showInputDialog(this, "Nom de l'attribut : ", "", JOptionPane.QUESTION_MESSAGE);
        if (nomAttribut != null) {
            if (nomAttribut.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomAttribut)) {
                JOptionPane.showMessageDialog(this, "Cet attribut existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                PHPClass c = controleur.getPhpControleur().getClasse((String) jList1.getSelectedValue());
                c.addAttribut(nomAttribut.replaceFirst(".", (nomAttribut.charAt(0) + "").toLowerCase()));
                list2.addElement(nomAttribut.replaceFirst(".", (nomAttribut.charAt(0) + "").toLowerCase()));
            }
        }
        actualiser();
    }

    private void afficherFenetreSupprimerAttribut() {
        String nomClasse = (String) jList1.getSelectedValue();
        String nomAttribut = (String) jList2.getSelectedValue();
        if (JOptionPane.showConfirmDialog(this, "Voulez vous vraiment supprimer l'attribut : " + nomAttribut, "Supprimer attribut", JOptionPane.OK_CANCEL_OPTION) == 0) {
            controleur.getPhpControleur().removeAttribut(nomClasse, nomAttribut);
            list2.removeElement(nomAttribut);
        }
        actualiser();
    }

    private void afficherFenetreModifierAttribut() {
        String nomClasse = (String) jList1.getSelectedValue();
        String oldNomAttribut = (String) jList2.getSelectedValue();
        String nomAttribut = JOptionPane.showInputDialog(this, "Nom de l'attribut", oldNomAttribut);
        if (nomAttribut != null) {
            if (nomAttribut.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous n'avez entré aucune valeur.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else if (controleur.existLien(nomAttribut)) {
                JOptionPane.showMessageDialog(this, "Cet attribut existe déjà.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                controleur.getPhpControleur().updateAttribut(nomClasse, oldNomAttribut, nomAttribut.replaceFirst(".", (nomAttribut.charAt(0) + "").toLowerCase()));
                list2.removeElement(oldNomAttribut);
                list2.addElement(nomAttribut.replaceFirst(".", (nomAttribut.charAt(0) + "").toLowerCase()));
            }
        }
        actualiser();
    }

    private void afficherEnregistrerProjet() {

    }

    public void initAll() {
        jList1.setModel(list1);
        jList2.setModel(list2);
        jList3.setModel(list3);
        jList4.setModel(list4);
        actualiser();
    }

    public void demanderNomProjet() {
        String nomProjet = "";
        while (nomProjet.equals("")) {
            nomProjet = JOptionPane.showInputDialog(this, "Nom du projet", "");
            if (nomProjet == null) {
                System.exit(0);
            } else if (nomProjet.equals("")) {
                JOptionPane.showMessageDialog(this, "Vous devez donner un nom à votre projet.", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                controleur.setNomProjet(nomProjet);
                setNomProjet(nomProjet);
            }
        }
    }

    private void actualiserList2() {
        list2.removeAllElements();
        if (jList1.getSelectedIndices().length > 0) {
            PHPClass c = controleur.getPhpControleur().getClasse((String) jList1.getSelectedValue());
            for (String s : c.getLesAttributs()) {
                list2.addElement(s);
            }
        }
    }

    private void afficherFenetreExporterProjet() throws IOException {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jFileChooser.setAcceptAllFileFilterUsed(false);
        if (jFileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): "
                    + jFileChooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : "
                    + jFileChooser.getSelectedFile());
            controleur.exporterProjet(jFileChooser.getSelectedFile());
        } else {
            JOptionPane.showMessageDialog(this, "Projet non sauvegardé", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setNomProjet(String nomProjet) {
        jLabel5.setText(nomProjet);
        jLabel6.setText(nomProjet);
        jTextField2.setText(nomProjet);
    }

    private void setNomSite() {
        if (jTextField2.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Le titre ne peut pas être vide.", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            controleur.setNomSite(jTextField2.getText());
        }
    }
    
}
